PostHub/testing/posts/urls.py
from django.urls import path
from . import views

app_name='posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('newpost',views.newpost,name='newpost'),
    path('<slug:slug>',views.posts,name='list')
   
]

PostHub/testing/testing/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',views.home,name='home'),
    path('posts/',include('posts.urls')),
    path('users/',include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PostHub/testing/users/urls.py
from django.urls import path
from . import views

app_name='users'
urlpatterns = [
    path('register', views.register, name='register'),
    path('login',views.login_view,name='login'),
    path('logout',views.logout,name='logout')
]

PostHub/testing/posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    title= models.CharField(max_length=100)
    body=models.TextField()
    time=models.DateTimeField(auto_now=True)
    slug=models.SlugField(unique=True)
    image=models.ImageField(blank=True)
    author = models.ForeignKey(User,on_delete = models.CASCADE,default=None)
  
    
    def __str__(self) :
        return self.title

PostHub/testing/users/models.py
from django.db import models

# Create your models here.

class UserModel(models.Model):
    name = models.CharField(max_length=100,unique=True)
    email = models.EmailField(max_length=100,blank=True)
    password = models.CharField(max_length=100)
    

PostHub/testing/posts/forms.py
from . import models
from django import forms


class NewPost(forms.ModelForm):
    class Meta:
        model=models.Post
        fields=['title','body','slug','image']

PostHub/testing/users/forms.py
from .models import UserModel
# from django.db import models
from django import forms

class UserPost(forms.ModelForm):
    class Meta:
        model=UserModel
        fields=['name','email','password']

PostHub/testing/posts/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def index(request):
    # return HttpResponse("Welocme to my posts")
    Posts=Post.objects.all()
    return render(request,'posts/post.html',{
        'posts':Posts
    })

def posts(request,slug):
    Posts=Post.objects.get(slug=slug)
    return render(request,'posts/list.html',{
        'post':Posts
    })

@login_required(login_url='/users:login')
def newpost(request):
    if request.method=='POST':
        form = forms.NewPost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False) 
            newpost.author = request.user 
            newpost.save()
            return redirect('posts:list')
        
        return redirect('posts:index')
    else:
        form = forms.NewPost()
    return render(request,'posts/newpost.html',{
        'form':form
    })

PostHub/testing/testing/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(reuqest):
    return render(reuqest,'home.html')

PostHub/testing/users/views.py
from django.shortcuts import render,redirect
# from .forms import UserPost
from django.urls import reverse

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout 
from django.contrib.auth import login

from django.contrib.auth.decorators import login_required



# Create your views here.
def register(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid:
            user = form.save()
            login(request,user)
            return redirect(reverse('posts:index'))
    else:
           form=UserCreationForm()
     
    return render(request, 'users/index.html',{
            'form':form
        })
    
def login_view(request):
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid:
            # user=form.get_user()
            login(request,form.get_user())
            return redirect('posts:index')
    else:
        form=AuthenticationForm()
    return render(request,'users/login.html',{
        'form':form
    })

def logout(request):
    if request.method=='POST': 
        logout(request)
        return redirect('users/login')

PostHub/testing/posts/templates/posts/list.html
<!DOCTYPE html>
<html lang="en">
    {% load static %} 
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Document</title>
  <link rel="stylesheet" href="{% static 'post/style.css'%}">
</head>
<body>

    {% if post.image %}
    <img class="myimage" src="{{ post.image.url }}" alt="myimage">
    {% else %}
   <img class="myimage" src="{% static 'default.jpg' %}" alt="No image available">
    {% endif %}

    <h1> {{post.title}} </h1>
    <p>by {{ post.author }}</p>
    {{post.body}}
    {{post.time}}
  
    
</body>
</html>

PostHub/testing/posts/templates/posts/newpost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h1>New Post</h1>
<form action="{% url 'posts:newpost' %}" method='post'  enctype="multipart/form-data" >
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Create Post">
</form>
    
</body>
</html>

PostHub/testing/posts/templates/posts/post.html
<!DOCTYPE html>
{%load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'post/style.css' %}">
</head>
<body>
    <h1>Welcometo my posts</h1>
    {%for post in posts%}
    <h1> 
        <a href="{% url 'posts:list' slug=post.slug %}" >
        {{post.title}}
    </a>
    <p> by {{post.author }}</p>
 </h1>
    {{post.body}}
    {{post.time}}
   
    {%empty%}
    <div><strong>No posts</strong></div>
    {%endfor%}
    
</body>
</html>

PostHub/testing/templates/home.html
{% extends  'layout.html'%}

{% block body %}
<h1>Welcome to my home page</h1>
{% endblock  %}

PostHub/testing/templates/layout.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'users/style.css' %}">
    {% endblock %}
</head>

<body>
    <nav>
        <ul>
            {% if user.is_authenticated %}
            <li><a href="/"><span role='img' aria-label='Home' title=Home>🏠 </span> </a></li> |
            <li><a href="/"><span role='img' aria-label='About' title=About>😘 </span> </a></li> |
            <li><a href="{% url 'posts:index'%}"><span role='img' aria-label='Posts' title=Contact Us>📰 </span> </a>
            </li> |

            <li><a href="{% url 'users:logout'%}"><span role='img' aria-label='Logout' title='Logout'> 🖐 </span></a>
            </li> |

            <li><a href="{% url 'posts:newpost'%}"><span role='img' aria-label='New Post' title'New Post'> 🆕
                    </span></a></li>
            {% endif %}
            <li><a href="{% url 'users:login'%}"><span role='img' aria-label='Login' title='Login'> 🔑 </span></a></li>
            |
            <li><a href="{%url 'users:register' %}"><span role='img' aria-label='Register' title=Register> 🔒
                    </span></a></li>
        </ul>
    </nav>
    {% block body %}{% endblock %}
</body>

</html>

PostHub/testing/users/templates/users/index.html
{% extends "users/layout.html" %}

{% block title %}
<title>Register User</title>
{% endblock %}


{% block body %}
<h1>Register a new user</h1>
<form action="{%url 'users:register'%}" method='post'>
    {% csrf_token %}

{{form.as_p}}
<button>Submit</button>
</form>

{% endblock %}

PostHub/testing/users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'users/style.css' %}">
    {% endblock %}
</head>
<body>
 
    {% block body %}{% endblock %}
</body>
</html>

PostHub/testing/users/templates/users/login.html
{% extends "layout.html" %}
{% block title %}
Login Page

{% endblock %}


{% block body %}
<h1>Login Here</h1>
<form action="{% url 'users:login'%}" method='post'>
{% csrf_token %}
{{form}}

<button>Login</button>
</form>



{% endblock %}